version: "3"
services:
  web:
    build: .
    labels:
      - "virtual.host=cs464.0xadd1e.me"
      - "virtual.port=8080"
      - "virtual.tls-email=0xadd1e@gmail.com"
networks:
  default:
    external:
      name: big_net
